### ISSUE TITLE
Clavicus is missing textures for his fingernails

### ISSUE THREAD

**Issue by ghost** [magicaldave/propaganda-machine-2024#7]
![image](https://github.com/user-attachments/assets/bfed9ba2-76bd-4b82-ab77-e8b3c1d58058)
![image](https://github.com/user-attachments/assets/99ae48b8-2c00-40fd-a7f9-aab8bd586211)

**Comment by ghost** [comment]
`Failed to open image: Resource 'textures/bb/bb_handm_he.dds' not found`

**Comment by Capostrophic** [comment]
ada4eda
